sudo: false
language: go

go:
  - "1.10.x"
  - "1.x"
  - master

git:
  depth: 5
  submodules: false

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      go: master

before_install:
  - env | sort

install:
  - time go install -i ./bin/jcms
  - time go get -t -v ./lib/...

script:
  - time go vet ./bin/jcms ./lib/...
  - time go test ./lib/...
  - time go test -race ./lib/...
