language: go

go:
  - "1.10.x"
  - "1.x"

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3

install:
  - time go install -i ./bin/jcms
  - time go get -t -v ./lib/...

script:
  - time go vet ./lib/...
  - time go test ./lib/...
  - time go test -race ./lib/...
