# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: "build{build}"

branches:
  only:
    - master

clone_folder: c:\golang\src\github.com\jrmsdev\go-jcms
clone_depth: 5

environment:
  global:
    GOPATH: C:\golang
    GETH_ARCH: amd64
    GOARCH: amd64
    CGO_ENABLED: 1
    MSYS2_ARCH: x86_64
    MSYS2_BITS: 64
    MSYSTEM: MINGW64
    PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
  matrix:
    - GOVERSION: "1.10.x"
    - GOVERSION: "1.x"
    - GOVERSION: master

matrix:
  fast_finish: true

install:
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - gcc --version

build_script:
  - echo %time%
  - go install -i ./bin/jcms
  - echo %time%
  - go get -t -v ./lib/...
  - echo %time%

after_build:
  - 7z a -tzip jcms-windows-%GOARCH%-$(version).zip %GOPATH%\bin\jcms.exe %GOPATH%\pkg\windows_amd64\github.com\jrmsdev\go-jcms\ -mx9

test_script:
  - echo %time%
  - go vet ./lib/...
  - echo %time%
  - go test ./lib/...
  - echo %time%
  - go test -race ./lib/...
  - echo %time%

artifacts:
  - path: 'jcms-windows-*.zip'

deploy: off
