# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: "build{build}"

branches:
  only:
    - master

clone_folder: c:\golang\src\github.com\jrmsdev\go-jcms
clone_depth: 5

environment:
  global:
    GOPATH: C:\golang
    GOARCH: amd64
  matrix:
    - GOROOT: C:\go110
    - GOROOT: C:\go

matrix:
  fast_finish: true

install:
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;%GOROOT%\bin;%PATH%
  - go version
  - go env
  - gcc --version

build_script:
  - echo %time%
  - go install -i ./bin/jcms
  - echo %time%
  - go get -t -v ./lib/...
  - echo %time%

after_build:
  - 7z a -tzip jcms-windows-%GOARCH%-build%APPVEYOR_BUILD_NUMBER%.zip %GOPATH%\bin\jcms.exe %GOPATH%\pkg\windows_amd64\github.com\jrmsdev\go-jcms\ -mx9

test_script:
  - echo %time%
  - go vet ./lib/...
  - echo %time%
  - go test ./lib/...
  - echo %time%
  - go test -race ./lib/...
  - echo %time%

artifacts:
  - path: 'jcms-windows-*.zip'

deploy: off
