// Code generated by "stringer -type MiddlewareAction"; DO NOT EDIT.

package middleware

import "strconv"

const _MiddlewareAction_name = "ACTION_PREACTION_POST"

var _MiddlewareAction_index = [...]uint8{0, 10, 21}

func (i MiddlewareAction) String() string {
	if i < 0 || i >= MiddlewareAction(len(_MiddlewareAction_index)-1) {
		return "MiddlewareAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MiddlewareAction_name[_MiddlewareAction_index[i]:_MiddlewareAction_index[i+1]]
}
